name: nowy
permissions:
- weight.10
- command.he.home
- command.he.sethome
- command.he.delhome
- command.he.listhomes
- home.limit.1
- command.he.back
- command.he.afk
- command.he.spawn
- command.he.warp
- command.he.warps
- command.he.listwarps
- command.he.kit
- command.he.kits
- command.he.rules
- command.he.playtime
- command.he.page
- command.he.pcallback
- ravenforge.rtp
prefixes:
- '&7[Nowy] ':
    priority: 10
meta:
- xaero.pac_max_claims:
    value: '4'
- xaero.pac_max_forceloads:
    value: '0'
